In [1]:
import numpy as np

In [2]:
import pyiron

In [3]:
pyiron.__file__

'/u/janj/pyiron/plugins/pyiron/pyiron/__init__.py'

In [4]:
from pyiron import Project

In [5]:
pr = Project('lib')

In [6]:
pr.remove_jobs(recursive=True)

In [7]:
pr.set_logging_level('DEBUG')

In [8]:
basis = pr.create_ase_bulk('Al', cubic=True).repeat([8,8,8])

In [9]:
len(basis)

2048

In [10]:
job = pr.create_job(pr.job_type.Lammps, 'lmp')

In [11]:
job._enable_mpi_log = True

In [12]:
job.structure = basis

In [13]:
job.potential = 'Al_Mg_Mendelev_eam'

In [14]:
job.server.run_mode.interactive = True

In [15]:
job.server.run_mode

'interactive'

In [16]:
job.server.cores = 2

In [17]:
job.run()

2020-02-08 10:08:41,287 - pyiron_log - INFO - run job: lmp id: None, status: initialized
2020-02-08 10:08:41,497 - pyiron_log - INFO - run job: lmp id: 4891969, status: created
2020-02-08 10:08:41,568 - pyiron_log - DEBUG - Lammps library: clear


The job lmp was saved and received the ID: 4891969


2020-02-08 10:08:41,952 - pyiron_log - DEBUG - Lammps library: units metal
2020-02-08 10:08:41,960 - pyiron_log - DEBUG - Lammps library: dimension 3
2020-02-08 10:08:41,968 - pyiron_log - DEBUG - Lammps library: boundary p p p
2020-02-08 10:08:41,976 - pyiron_log - DEBUG - Lammps library: atom_style atomic
2020-02-08 10:08:41,984 - pyiron_log - DEBUG - Lammps library: atom_modify map array
2020-02-08 10:08:41,992 - pyiron_log - DEBUG - Lammps library: region 1 block 0.0 32.4 0.0 32.4 0.0 32.4 units box
2020-02-08 10:08:42,000 - pyiron_log - DEBUG - Lammps library: create_box 2 1
2020-02-08 10:08:42,008 - pyiron_log - DEBUG - Lammps library: mass   1 26.981538
2020-02-08 10:08:42,015 - pyiron_log - DEBUG - Lammps library: mass   2 1.000000
2020-02-08 10:08:42,023 - pyiron_log - DEBUG - Lammps library: create_atoms 1 random 2048 12345 1
2020-02-08 10:08:42,047 - pyiron_log - DEBUG - Lammps library: change_box all remap
2020-02-08 10:08:42,054 - pyiron_log - DEBUG - Lammps library: fix e

In [18]:
basis.positions[0]

array([0., 0., 0.])

In [19]:
basis.positions[0] += [0.1, 0.1, 0.1]

In [20]:
job.structure = basis

In [21]:
job.output.cells

array([[[3.24000000e+01, 1.98392781e-15, 1.98392781e-15],
        [0.00000000e+00, 3.24000000e+01, 1.98392781e-15],
        [0.00000000e+00, 0.00000000e+00, 3.24000000e+01]]])

In [22]:
job.output.positions

array([[[ 0.   ,  0.   ,  0.   ],
        [ 0.   ,  2.025,  2.025],
        [ 2.025,  0.   ,  2.025],
        ...,
        [28.35 , 30.375, 30.375],
        [30.375, 28.35 , 30.375],
        [30.375, 30.375, 28.35 ]]])

In [23]:
job.run()

2020-02-08 10:08:42,610 - pyiron_log - INFO - run job: lmp id: 4891969, status: running
2020-02-08 10:08:42,767 - pyiron_log - DEBUG - Generic library: cell changed!
2020-02-08 10:08:42,769 - pyiron_log - DEBUG - Lammps library: change_box all x final 0 32.400000 y final 0 32.400000 z final 0 32.400000 units box
2020-02-08 10:08:42,778 - pyiron_log - DEBUG - Generic library: positions changed!
2020-02-08 10:08:42,785 - pyiron_log - DEBUG - Lammps library: change_box all remap
2020-02-08 10:08:42,793 - pyiron_log - DEBUG - Lammps library: run 0 


In [24]:
job.output.energy_tot

array([-6984.92519058, -6984.8627293 ])

In [25]:
pr.job_table()

2020-02-08 10:08:43,115 - pyiron_log - DEBUG - sql_query: {'project': 'janj/pyiron/projects/2020/2020-02-07-lammps-mpi-lib/lib/%'}


id   status chemicalformula  job subjob projectpath  \
0  4891969  running          Al2048  lmp   /lmp    /cmmc/u/   

                                                    project  \
0  janj/pyiron/projects/2020/2020-02-07-lammps-mpi-lib/lib/   

                   timestart timestop totalcputime        computer hamilton  \
0 2020-02-08 10:08:41.373562     None         None  janj@cmti001#2   Lammps   

  hamversion parentid masterid  
0        0.1     None     None

In [26]:
job.interactive_close()